name: Approve Pull Request
author: juliangruber
description: 'A GitHub Action for approving pull requests'
branding:
  icon: 'git-pull-request'
  color: green
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  approve-label:
    description: 'Label to Auto-approve PRs for'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
