name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      number:
        required: true
        type: number
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - name: Approve Pull Request
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ inputs.number || 1 }}
